services:
  # stack:
  #   build:
  #     context: ./stack
  #     dockerfile: Dockerfile
  #   container_name: PersonaStack
  #   # restart: on-failure
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - net
  #   env_file:
  #     - .env.production
  postgres-db:
    # Use a custom Docker build context for PostgreSQL.
    build: ./contrib/postgresql
    container_name: postgres-db
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: ./contrib/qdrant/config/config.yaml
    volumes:
      - ./qdrant_data:/qdrant_data
    networks:
      - net
  unstructured-api:
    env_file:
      - .env.production
    image: quay.io/unstructured-io/unstructured-api:latest
    container_name: unstructured-api
    environment:
      - UNSTRUCTURED_API_KEY=${UNSTRUCTURED_API_KEY}
    ports:
      - 8000:8000
    networks:
      - net
  # langfuse-server:
  #   image: langfuse/langfuse:latest
  #   container_name: langfuse
  #   platform: linux/amd64
  #   depends_on:
  #     postgres-db:
  #       condition: service_healthy
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - net
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/langfuse
  #     - NEXTAUTH_SECRET=mysecret
  #     - SALT=mysalt
  #     - NEXTAUTH_URL=http://localhost:3000
  #     - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
  #     - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
  # phoenix:
  #   image: arizephoenix/phoenix:latest
  #   container_name: phoenix
  #   platform: linux/amd64
  #   depends_on:
  #     postgres-db:
  #       condition: service_healthy
  #   networks:
  #     - net
  #   ports:
  #     - 6006:6006 # PHOENIX_PORT
  #     - 4317:4317 # PHOENIX_GRPC_PORT
  #     - 9090:9090 # [Optional] PROMETHEUS PORT IF ENABLED
  #   environment:
  #     - PHOENIX_SQL_DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/phoenix
  #     - PHOENIX_WORKING_DIR=/phoenix
  # Uncomment if you want to run local models using ollama docker image
  # ollama:
  #   image: ollama/ollama
  #   container_name: embed-ollama
  #   ports:
  #     - 11435:11434
  #   volumes:
  #     - ./models:/root/.ollama/models

configs:
  qdrant_config:
    content: |
      log_level: INFO

networks:
  net:
volumes:
  qdrant_data:
    driver: local
  postgresql_data:
    driver: local
  langfuse_data:
    driver: local
  # models:
  #   driver: local
