[GLOBAL]
pants_version = "2.20.0"
backend_packages = [
  "pants.backend.shell",
  "pants.backend.shell.lint.shfmt",
  "pants.backend.shell.lint.shellcheck",

  "pants.backend.docker",
  "pants.backend.docker.lint.hadolint",

  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.autoflake",
  "pants.backend.python.typecheck.mypy",
]

[source]
root_patterns = ["/"]

[python]
# The default interpreter constraints for code in this repo. Individual targets can override
#  this with the `interpreter_constraints` field. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility.

# Modify this if you don't have Python 3.9 on your machine.
# This can be a range, such as [">=3.8,<3.11"], but it's usually recommended to restrict
# to a single minor version.
interpreter_constraints = ["CPython>=3.11,<3.12"]

# Enable the "resolves" mechanism, which turns on lockfiles for user code. See
# https://www.pantsbuild.org/docs/python-third-party-dependencies. This also adds the
# `generate-lockfiles` goal for Pants to generate the lockfile for you.
enable_resolves = true

resolves = { python-default = "constraints.txt"}

[python-bootstrap]
# We search for interpreters both on the $PATH and in the `$(pyenv root)/versions` folder.
#  If you're using macOS, you may want to leave off the <PATH> entry to avoid using the
#  problematic system Pythons. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path.
search_path = ["<PATH>", "<PYENV>"]

[test]
extra_env_vars = [
  "PERSONAFLOW_API_KEY="1234"
  "OPENAI_API_KEY=sk-test",
  "INTERNAL_DATABASE_DATABASE=TEST_DB",
  "INTERNAL_DATABASE_USER",
  "INTERNAL_DATABASE_PASSWORD",
  "INTERNAL_DATABASE_HOST",
  "INTERNAL_DATABASE_PORT",
  "INTERNAL_DATABASE_DATABASE",
  "INTERNAL_DATABASE_SCHEMA",
  "VECTOR_DB_HOST",
  "VECTOR_DB_PORT",
  "VECTOR_DB_NAME",
  "VECTOR_DB_COLLECTION_NAME",
  "VECTOR_DB_ENCODER_NAME",
  "VECTOR_DB_ENCODER_DIMENSIONS",
  "VECTOR_DB_ENCODER_MODEL",
  "VECTOR_DB_DEFAULT_NAMESPACE",
  "LANGGRAPH_RECURSION_LIMIT",
  "UNSTRUCTURED_API_KEY",
  "UNSTRUCTURED_BASE_URL"
  ]
