"""
migrations/script.py.mako
----------------------------


Alembic Migration Script Template

This script serves as a template for Alembic migrations. When Alembic auto-generates migration scripts, it uses
this template to structure the content. The generated script then gets saved in the 'versions' directory under 'migrations'.
Each script defines actions to be taken for both 'upgrade' (applying the migration) and 'downgrade' (reverting the migration).

"""

"""Auth

Revision ID: af0a5f3e2816
Revises: 1091347b4ab9
Create Date: 2024-06-27 14:09:38.460045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import (
    postgresql,
)  # Import additional modules dynamically based on the migration's needs.

# Revision identifiers, used by Alembic to identify the migration script.
revision = "af0a5f3e2816"  # The ID of this revision (migration).
down_revision = (
    "1091347b4ab9"  # The ID of the previous revision. Specifies ordering of migrations.
)
branch_labels = None  # Labels that can group revisions together.
depends_on = None  # If this revision depends on another one, it is referenced here.


# Function to handle the 'upgrade' operation.
# This contains the operations to be performed when moving to this version from the previous version.
def upgrade() -> None:
    op.create_table(
        "blacklist",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="A unique identifier for the checkpoint. It's a UUID type and is automatically generated by the database.",
        ),
        sa.Column(
            "token_id",
            sa.String(),
            nullable=False,
            comment="The ID of the token to be blacklisted.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="The timestamp when the token was blacklisted.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="The timestamp when the token was last updated.",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personaflow",
    )
    op.create_index(
        op.f("ix_personaflow_blacklist_token_id"),
        "blacklist",
        ["token_id"],
        unique=False,
        schema="personaflow",
    )

    op.alter_column("users", "email", unique=True, schema="personaflow")

    op.create_index(
        "ix_personaflow_users_email",
        "users",
        ["email"],
        unique=True,
        schema="personaflow",
    )

    op.execute(
        """
        ALTER TABLE personaflow.users
        ALTER COLUMN password
        TYPE BYTEA
        USING password::bytea
        """
    )

    op.alter_column(
        "users", "password", new_column_name="hashed_password", schema="personaflow"
    )

    # ### end Alembic commands ###  # Operations to upgrade the database schema.


# Function to handle the 'downgrade' operation.
# This contains the operations to revert the changes introduced in the 'upgrade' function.
def downgrade() -> None:
    op.alter_column(
        "users", "hashed_password", new_column_name="password", schema="personaflow"
    )
    op.execute(
        """
        ALTER TABLE personaflow.users
        ALTER COLUMN password
        TYPE VARCHAR
        USING password::varchar
        """
    )
    op.drop_index(
        "ix_personaflow_users_email", table_name="users", schema="personaflow"
    )
    op.alter_column("users", "email", unique=False, schema="personaflow")
    op.drop_index(
        op.f("ix_personaflow_blacklist_token_id"),
        table_name="blacklist",
        schema="personaflow",
    )
    op.drop_table("blacklist", schema="personaflow")
    # ### end Alembic commands ###  # Operations to downgrade the database schema.
