"""
migrations/script.py.mako
----------------------------


Alembic Migration Script Template

This script serves as a template for Alembic migrations. When Alembic auto-generates migration scripts, it uses
this template to structure the content. The generated script then gets saved in the 'versions' directory under 'migrations'.
Each script defines actions to be taken for both 'upgrade' (applying the migration) and 'downgrade' (reverting the migration).

"""

"""Add relationships

Revision ID: e1338e81c83d
Revises: dc27d3e10363
Create Date: 2024-06-13 16:27:50.041673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import (
    postgresql,
)  # Import additional modules dynamically based on the migration's needs.

# Revision identifiers, used by Alembic to identify the migration script.
revision = "e1338e81c83d"  # The ID of this revision (migration).
down_revision = (
    "dc27d3e10363"  # The ID of the previous revision. Specifies ordering of migrations.
)
branch_labels = None  # Labels that can group revisions together.
depends_on = None  # If this revision depends on another one, it is referenced here.


# Function to handle the 'upgrade' operation.
# This contains the operations to be performed when moving to this version from the previous version.
def upgrade() -> None:
    op.alter_column(
        "threads",
        "assistant_id",
        type_=sa.UUID(),
        postgresql_using="assistant_id::uuid",
        schema="personaflow",
    )
    op.alter_column(
        "checkpoints",
        "thread_id",
        type_=sa.UUID(),
        postgresql_using="thread_id::uuid",
        schema="personaflow",
    )
    op.alter_column(
        "messages",
        "thread_id",
        type_=sa.UUID(),
        postgresql_using="thread_id::uuid",
        schema="personaflow",
    )
    op.alter_column(
        "messages",
        "assistant_id",
        type_=sa.UUID(),
        postgresql_using="assistant_id::uuid",
        schema="personaflow",
    )

    # assistants -> users
    op.create_foreign_key(
        "fk_assistants_users",
        "assistants",
        "users",
        ["user_id"],
        ["user_id"],
        source_schema="personaflow",
        referent_schema="personaflow",
    )

    # files -> users
    op.create_foreign_key(
        "fk_files_users",
        "files",
        "users",
        ["user_id"],
        ["user_id"],
        source_schema="personaflow",
        referent_schema="personaflow",
    )

    # threads -> users
    op.create_foreign_key(
        "fk_threads_users",
        "threads",
        "users",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
        source_schema="personaflow",
        referent_schema="personaflow",
    )

    # threads -> assistants
    op.create_foreign_key(
        "fk_threads_assistants",
        "threads",
        "assistants",
        ["assistant_id"],
        ["id"],
        source_schema="personaflow",
        referent_schema="personaflow",
    )

    # checkpoints -> threads
    op.create_foreign_key(
        "fk_checkpoints_threads",
        "checkpoints",
        "threads",
        ["thread_id"],
        ["id"],
        ondelete="CASCADE",
        source_schema="personaflow",
        referent_schema="personaflow",
    )
    # checkpoints -> users
    op.create_foreign_key(
        "fk_checkpoints_users",
        "checkpoints",
        "users",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
        source_schema="personaflow",
        referent_schema="personaflow",
    )

    # messages -> threads
    op.create_foreign_key(
        "fk_messages_threads",
        "messages",
        "threads",
        ["thread_id"],
        ["id"],
        ondelete="CASCADE",
        source_schema="personaflow",
        referent_schema="personaflow",
    )

    # messages -> assistants
    op.create_foreign_key(
        "fk_messages_assistants",
        "messages",
        "assistants",
        ["assistant_id"],
        ["id"],
        source_schema="personaflow",
        referent_schema="personaflow",
    )
    # messages -> users
    op.create_foreign_key(
        "fk_messages_users",
        "messages",
        "users",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
        source_schema="personaflow",
        referent_schema="personaflow",
    )


# Function to handle the 'downgrade' operation.
# This contains the operations to revert the changes introduced in the 'upgrade' function.
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Dropping foreign keys
    op.drop_constraint(
        "fk_messages_users", "messages", type_="foreignkey", schema="personaflow"
    )
    op.drop_constraint(
        "fk_messages_assistants", "messages", type_="foreignkey", schema="personaflow"
    )
    op.drop_constraint(
        "fk_messages_threads", "messages", type_="foreignkey", schema="personaflow"
    )

    op.drop_constraint(
        "fk_checkpoints_users", "checkpoints", type_="foreignkey", schema="personaflow"
    )
    op.drop_constraint(
        "fk_checkpoints_threads",
        "checkpoints",
        type_="foreignkey",
        schema="personaflow",
    )

    op.drop_constraint(
        "fk_threads_assistants", "threads", type_="foreignkey", schema="personaflow"
    )
    op.drop_constraint(
        "fk_threads_users", "threads", type_="foreignkey", schema="personaflow"
    )

    op.drop_constraint(
        "fk_files_users", "files", type_="foreignkey", schema="personaflow"
    )
    op.drop_constraint(
        "fk_assistants_users", "assistants", type_="foreignkey", schema="personaflow"
    )

    # Reverting column types from UUID to String
    op.alter_column(
        "messages",
        "assistant_id",
        type_=sa.String(),
        postgresql_using="assistant_id::text",
        schema="personaflow",
    )
    op.alter_column(
        "messages",
        "thread_id",
        type_=sa.String(),
        postgresql_using="thread_id::text",
        schema="personaflow",
    )
    op.alter_column(
        "checkpoints",
        "thread_id",
        type_=sa.String(),
        postgresql_using="thread_id::text",
        schema="personaflow",
    )
    op.alter_column(
        "threads",
        "assistant_id",
        type_=sa.String(),
        postgresql_using="assistant_id::text",
        schema="personaflow",
    )
